### PR TITLE
Todo interactive list

### PR DESCRIPTION
**Pull request by Bria222**
1. Used webpack to bundle JavaScript.
2. Used ES6 syntax.
3. Used ES6 modules to write modular JavaScript.
4. Added functionality to mark tasks as complete and to remove completed tasks only via javascript
5. Added edit functionality by enabling users to click on a task to edit and then save it to a local storage

### CODE REVIEW

**Review by brytebee — CHANGES_REQUESTED** [review]
Hi, @Bria222👋,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

# Status: Invalid Code Review Request



You have submitted a project, that cannot be thoroughly reviewed as it only presents only the `README.md` file for review. You can try to push all files to reflect as files changed or create and push changes to another branch. Ensure they show up under the `files changed` tag on `GitHub` before requesting another review.

image

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Bria222** [comment]
@brytebee hi I completed the project and pushed it yesterday i mean i did everything yesterday even today's task i finished yesterday thats why i implemented all the project requirements and functionality

**Comment by brytebee** [comment]
Okay, great job @Bria222. I see more files there now, however, they are not files that can be reviewed. You need all files in the `src` directory.

**Comment by Bria222** [comment]
@brytebee the src is my entry point folder I have another folder inside with separate modules I have broken down my code into smaller blocks which are maintainable  bu i have now set my custom port

**Comment by Bria222** [comment]
@brytebee you mean i should remove them from  modules into the src folder

**Comment by Bria222** [comment]
@brytebee this is my folder structure the only files outside the src folder are the workflows and the main files
Screenshot (212)

**Review by VICTOR-CHUKWU — APPROVED** [review]
Hi @Bria222 , 
# STATUS: APPROVED! 🥇 💯 
done

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
